apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: your-eks-cluster
  region: eu-west-1

vpc:
  clusterEndpoints:
    publicAccess: true
    privateAccess: true

nodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 2
